services:
  tests:
    build: .
    volumes:
      - .:/app
    environment:
      - LUA_PATH=/app/?.lua;/app/?/init.lua;;
    command: lua5.3 tests/run_tests.lua

  dev:
    build: .
    volumes:
      - .:/app
    environment:
      - LUA_PATH=/app/?.lua;/app/?/init.lua;;
    command: /bin/sh
    stdin_open: true
    tty: true